// Generated by jextract

package org.apache.arrow.datafusion;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1 {

    static final FunctionDescriptor df_session_context_sql$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle df_session_context_sql$MH = RuntimeHelper.downcallHandle(
        "df_session_context_sql",
        constants$1.df_session_context_sql$FUNC
    );
}


